### ISSUE TITLE
Bukkit's permissions.yml isn't respected

### ISSUE THREAD

**Issue by theJ3H** [tastybento/askyblockIssues#958]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Paper 1.8.8
**Plugin version:**
3.0.9.4
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
New install
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
Vault, PermissionsEx
**Description of issue. What happened?**
ASkyblock doesn't respect permissions
**Steps to make this happen**

1. Set a permission in permissions.yml

```
test.permission:
       description: test
       default: op
       children:
          askyblock.island.controlpanel: true
```
2. Use a permission plugin (like Pex) to give users test.permission
3. Try to access control panel

**What do you think should happen?**
The plugin should respect permissions given by permissions.yml. Currently only Permission plugins using Vault are respected. Permissions.yml is a build-in bukkit feature, that should be supported. (see https://bukkit.gamepedia.com/Permissions.yml )
